language: node_js
node_js:
  - lts/*
services:
  - mysql
env:
  global:
    - NODE_ENV=test
before_install:
  - npm i npm -g
  - npm -v
  - npm i yarn -g
  - yarn -v
  - bash ./scripts/before-install.sh
  - mysql -e 'CREATE DATABASE database_test;'
script:
  - yarn lint
  - yarn start:test
  - yarn test
after_success:
  - bash ./scripts/deploy.sh
