language: node_js
node_js:
  - lts/*
services:
  - mysql
env:
  global:
    - NODE_ENV=test
before_install:
  - npm i npm yarn -g
  - mysql -e 'CREATE DATABASE database_test;'
script:
  - yarn lint
  - yarn start:test
  - yarn test
before_deploy:
  - bash ./scripts/before-deploy.sh
deploy:
  provider: script
  skip_cleanup: true
  script: ./scripts/deploy.sh
  on:
    branch: master
