language: node_js
node_js:
  - lts/*
services:
  - mysql
env:
  global:
    - NODE_ENV=test
before_install:
  - openssl aes-256-cbc -K $encrypted_d80369b7a19f_key -iv $encrypted_d80369b7a19f_iv
    -in travis_rsa.enc -out travis_rsa -d
  - mysql -e 'CREATE DATABASE database_test;'
script:
  - yarn lint
  - yarn start:test
  - yarn test
after_success:
  - bash deploy.sh
